### ISSUE TITLE
عدم نمایش برنامه در فهرست اپلیکیشنها

### ISSUE THREAD

**Issue by raminmjj** [mghiasi75/ApplicationDataManageTool#2]
سلام.
بعد از نصب برنامه در فهرست اپلیکیشنها این برنامه نمایش داده نمیشه.
با برنامه Interop Tools گوشی لومیا 640 رو آنلاک کردم. "این برنامه رو از استور نصب کردم نسخه پریویو"
ممنون میشم راهنمایی کنید.
میخوام دیتا برنامه outlook رو پاک کنم.
هیچ ایمیلی توش نیست اما حجمش به 500 مگ رسیده.
ببخشید. به دلیل نداشتن آدرس ایمیل شما، اینجا پیام فرستادم.
سپاس

**Comment by MahdiGhiasi** [comment]
احتمالن گوشی درست آنلاک نشده.
نسخه‌ی استور Interop Tools به تنهایی کافی نیست. 
[این راهنما ](https://www.microsoftlife.ir/introop-tools-jailbreak-windows-mobile-10/)رو دنبال کنید.
